apiVersion: v1
kind: Service
metadata:
  name: rates-test
  namespace: default
spec:
  selector:
    app: rates-test
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3001
      nodePort: 30000